### ISSUE TITLE
Implement toast message on redirect to dashboard page after payment

### ISSUE THREAD

**Issue by noisecapella** [mitodl/bootcamp-ecommerce#623] opened 2020-06-04 13:46 UTC
On `/pay` we have logic to check the status of the page and poll for the order status, so that we can notify the user when the order is fulfilled. We should do the same thing on the application dashboard page

**Comment by gsidebo** [comment] 2020-07-07 18:02
Partial duplicate of #658

**Closed by gsidebo** 2020-07-07 18:02 UTC
